DROP SEQUENCE PF_USER_SEQ;
DROP SEQUENCE PF_BOARD_SEQ;

DROP TABLE PF_BOARD;
DROP TABLE PF_USER;

CREATE SEQUENCE PF_USER_SEQ;
CREATE SEQUENCE PF_BOARD_SEQ;

CREATE TABLE PF_USER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(128) UNIQUE NOT NULL,
    USER_PW VARCHAR2(128) NOT NULL,
    USER_EMAIL VARCHAR2(256) UNIQUE NOT NULL,
    USER_TYPE VARCHAR2(128) NOT NULL,
    USER_ADDR VARCHAR2(1024),
    USER_EMAIL_HASH VARCHAR2(128) NOT NULL,
    USER_EMAIL_CHECK VARCHAR2(128) CHECK(USER_EMAIL_CHECK IN('TRUE','FALSE')),
    USER_IMG VARCHAR2(1024)
);

CREATE TABLE PF_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(1024) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    PROJECT_MONEY NUMBER NOT NULL,
    PROJECT_TERM NUMBER NOT NULL,
    PROJECT_START_DAY DATE NOT NULL,
    RECRUIT_DATE DATE NOT NULL,
    RECRUIT_PERSONNEL NUMBER NOT NULL,
    PROJECT_CATEGORY VARCHAR2(1024) NOT NULL,
    PROJECT_TYPE VARCHAR2(1024) NOT NULL,
    BOARD_FILE BLOB,
    PROJECT_STATE VARCHAR2(1024) NOT NULL,
    BOARD_REGDATE DATE NOT NULL,
    USER_NO NUMBER NOT NULL,
    
    CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO)
);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user1', 'user1', 'user1@naver.com', '투자자', NULL, 'FALSE', 'TRUE', NULL);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user2', 'user2', 'user2@naver.com', '파트너스', NULL, 'FALSE', 'TRUE', NULL);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user3', 'user3', 'user3@naver.com', '클라이언트', NULL, 'FALSE', 'TRUE', NULL);

COMMIT;