DROP SEQUENCE PF_USER_SEQ;
DROP SEQUENCE PF_BOARD_SEQ;
DROP SEQUENCE PF_PROFILE_SEQ;
DROP SEQUENCE PF_PORTFOLIO_SEQ;
DROP SEQUENCE PF_COIN_SEQ;
DROP SEQUENCE PF_TECHNOLOGY_SEQ;
DROP SEQUENCE PF_CAREER_SEQ;
DROP SEQUENCE PF_EDUCATION_SEQ;
DROP SEQUENCE PF_CERTIFICATE_SEQ;
DROP SEQUENCE PF_COMMENT_SEQ;
DROP SEQUENCE PF_MESSAGE_SEQ;
DROP SEQUENCE PF_INVEST_SEQ;
DROP SEQUENCE PF_EVALUATION_SEQ;
DROP SEQUENCE PF_APPLICANT_SEQ;

DROP TABLE PF_APPLICANT;
DROP TABLE PF_COMMENT;
DROP TABLE PF_INVEST;
DROP TABLE PF_MESSAGE;
DROP TABLE PF_CERTIFICATE;
DROP TABLE PF_EDUCATION;
DROP TABLE PF_CAREER;
DROP TABLE PF_TECHNOLOGY;
DROP TABLE PF_COIN;
DROP TABLE PF_PORTFOLIO;
DROP TABLE PF_PROFILE;
DROP TABLE PF_BOARD;
DROP TABLE PF_USER;
DROP TABLE PF_EVALUATION;

CREATE SEQUENCE PF_USER_SEQ;
CREATE SEQUENCE PF_INVEST_SEQ;
CREATE SEQUENCE PF_BOARD_SEQ;
CREATE SEQUENCE PF_PROFILE_SEQ;
CREATE SEQUENCE PF_PORTFOLIO_SEQ;
CREATE SEQUENCE PF_COIN_SEQ;
CREATE SEQUENCE PF_TECHNOLOGY_SEQ;
	alter sequence PF_TECHNOLOGY_SEQ increment by 10;
CREATE SEQUENCE PF_CAREER_SEQ;
	alter sequence PF_CAREER_SEQ increment by 10;
CREATE SEQUENCE PF_EDUCATION_SEQ;
	alter sequence PF_EDUCATION_SEQ increment by 10;
CREATE SEQUENCE PF_CERTIFICATE_SEQ;
	alter sequence PF_CERTIFICATE_SEQ increment by 10;
CREATE SEQUENCE PF_COMMENT_SEQ;
CREATE SEQUENCE PF_MESSAGE_SEQ;
CREATE SEQUENCE PF_EVALUATION_SEQ;
CREATE SEQUENCE PF_APPLICANT_SEQ;


CREATE TABLE PF_USER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(128) UNIQUE NOT NULL,
    USER_PW VARCHAR2(128) NOT NULL,
    USER_EMAIL VARCHAR2(256) UNIQUE NOT NULL,
    USER_TYPE VARCHAR2(128) NOT NULL,
    USER_ADDR VARCHAR2(1024),
    USER_EMAIL_HASH VARCHAR2(128) NOT NULL,
    USER_EMAIL_CHECK VARCHAR2(128) CHECK(USER_EMAIL_CHECK IN('TRUE','FALSE')),
    USER_IMG VARCHAR2(1024),
    USER_NAME VARCHAR2(1024),
    USER_SEX VARCHAR2(1024),
    USER_BIRTH VARCHAR2(1024),
    USER_UPTYPE VARCHAR2(1024)
);
CREATE TABLE PF_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(1024) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    PROJECT_MONEY NUMBER NOT NULL,
    PROJECT_TERM NUMBER NOT NULL,
    PROJECT_START_DAY VARCHAR2(1024) NOT NULL,
    RECRUIT_DATE VARCHAR2(1024) NOT NULL,
    RECRUIT_PERSONNEL NUMBER NOT NULL,
    PROJECT_CATEGORY VARCHAR2(1024) NOT NULL,
    PROJECT_TYPE VARCHAR2(1024) NOT NULL,
    BOARD_FILE VARCHAR2(1024),
    PROJECT_STATE VARCHAR2(1024) NOT NULL,
    BOARD_REGDATE DATE NOT NULL,
    USER_NO NUMBER NOT NULL,
    LIKEUSER_NO NUMBER,
    BOARD_LIKE VARCHAR2(30), 
    
    CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO) 
);

CREATE TABLE PF_PROFILE(
    PROFILE_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    PROFILE_JOB VARCHAR2(128),
    PROFILE_ACTIVITY VARCHAR2(128),
    PROFILE_INTRO VARCHAR2(4000),
    
    CONSTRAINT FK_USER_NO2 FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO)
);
CREATE TABLE PF_PORTFOLIO(
    PORTFOLIO_NO NUMBER PRIMARY KEY,
    PROFILE_NO NUMBER NOT NULL,
    PORTFOLIO_TITLE VARCHAR2(128) NOT NULL,
    PORTFOLIO_START_DAY DATE NOT NULL,
    PORTFOLIO_END_DAY DATE NOT NULL,
    PORTFOLIO_PARTICIPATION NUMBER NOT NULL,
    PORTFOLIO_CONTENT VARCHAR2(4000) NOT NULL,
    PORTFOLIO_FILE VARCHAR2(4000),
    
    CONSTRAINT FK_PROFILE_NO FOREIGN KEY(PROFILE_NO) REFERENCES PF_PROFILE(PROFILE_NO)
);
CREATE TABLE PF_COIN(
	COIN_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	COIN_REGDATE DATE NOT NULL,
	COIN_MONEY NUMBER NOT NULL,
	COIN_STATE VARCHAR2(1024) NOT NULL,
    
    CONSTRAINT FK_USER_NO3 FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO)
);
CREATE TABLE PF_TECHNOLOGY(
    TECH_NO NUMBER PRIMARY KEY,
    PROFILE_NO NUMBER NOT NULL,
    TECH_TYPE VARCHAR2(128) NOT NULL,
    TECH_SKILL VARCHAR2(128) NOT NULL,
    TECH_EXP VARCHAR2(128) NOT NULL,
    
    CONSTRAINT FK_PROFILE_NO2 FOREIGN KEY(PROFILE_NO) REFERENCES PF_PROFILE(PROFILE_NO)
);
CREATE TABLE PF_CAREER(
    CAREER_NO NUMBER PRIMARY KEY,
    PROFILE_NO NUMBER NOT NULL,
    CAREER_COMPANY VARCHAR2(128) NOT NULL,
    CAREER_DEPT VARCHAR2(128) NOT NULL,
    CAREER_SPOT VARCHAR2(128) NOT NULL,
    CAREER_HIREDATE VARCHAR2(128) NOT NULL,
    CAREER_FIREDATE VARCHAR2(128),
    
    CONSTRAINT FK_PROFILE_NO3 FOREIGN KEY(PROFILE_NO) REFERENCES PF_PROFILE(PROFILE_NO)
);
CREATE TABLE PF_EDUCATION(
    EDU_NO NUMBER PRIMARY KEY,
    PROFILE_NO NUMBER NOT NULL,
    EDU_NAME VARCHAR2(128) NOT NULL,
    EDU_STATE VARCHAR2(128) NOT NULL,
    EDU_MAJOR VARCHAR2(128) NOT NULL,
    EDU_HIREDATE VARCHAR2(128) NOT NULL,
    EDU_FIREDATE VARCHAR2(128),
    
    CONSTRAINT FK_PROFILE_NO4 FOREIGN KEY(PROFILE_NO) REFERENCES PF_PROFILE(PROFILE_NO)
);

CREATE TABLE PF_INVEST(
    INVEST_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    INVEST_MONEY NUMBER NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    
    CONSTRAINT FK_USER_NO6 FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO),
    CONSTRAINT FK_BOARD_NO1 FOREIGN KEY(BOARD_NO) REFERENCES PF_BOARD(BOARD_NO)
);

CREATE TABLE PF_CERTIFICATE(
    CERTIFICATE_NO NUMBER PRIMARY KEY,
    PROFILE_NO NUMBER NOT NULL,
    CERTIFICATE_NAME VARCHAR2(128) NOT NULL,
    CERTIFICATE_AGENCY VARCHAR2(128) NOT NULL,
    CERTIFICATE_ISSUEDDATE VARCHAR2(128) NOT NULL,
    
    CONSTRAINT FK_PROFILE_NO5 FOREIGN KEY(PROFILE_NO) REFERENCES PF_PROFILE(PROFILE_NO)
);
CREATE TABLE PF_COMMENT (
    COMMENT_NO NUMBER NOT NULL,
    COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    COMMENT_REGDATE VARCHAR2(100) NOT NULL,
    
     CONSTRAINT FK_USER_NO5 FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO),
     CONSTRAINT FK_BOARD_NO FOREIGN KEY(BOARD_NO) REFERENCES PF_BOARD(BOARD_NO)
);

CREATE TABLE PF_MESSAGE(
	MESSAGE_NO NUMBER PRIMARY KEY, --쪽지 번호
	MESSAGE_CONTENT VARCHAR2(500) NOT NULL, --쪽지 내용
	MESSAGE_READER VARCHAR2(100) NOT NULL, --받는 사람
	MESSAGE_SENDER VARCHAR2(100) NOT NULL, --보낸 사람
	MESSAGE_SENDDATE DATE NOT NULL, --보낸 날짜
	MESSAGE_STATE VARCHAR2(100) NOT NULL --쪽지 상태(안읽음 / 읽음)
);

CREATE TABLE PF_EVALUATION(
    EVALUATION_NO NUMBER PRIMARY KEY,
    EVALUATION_WRITER VARCHAR2(256) NOT NULL,
    EVALUATION_OBJECT VARCHAR2(256) NOT NULL,
    EVALUATION_ITEM1 NUMBER NOT NULL,
    EVALUATION_ITEM2 NUMBER NOT NULL,
    EVALUATION_ITEM3 NUMBER NOT NULL,
    EVALUATION_CONTENT VARCHAR2(4000) NOT NULL
    
);

CREATE TABLE PF_APPLICANT(
    APPLICANT_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    APPLICANT_STATE VARCHAR2(128) NOT NULL,
    
    CONSTRAINT FK_USER_NO20 FOREIGN KEY(USER_NO) REFERENCES PF_USER(USER_NO),
    CONSTRAINT FK_BOARD_NO20 FOREIGN KEY(BOARD_NO) REFERENCES PF_BOARD(BOARD_NO)
);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user1', 'user1', 'user1@naver.com', '투자자', NULL, 'FALSE', 'TRUE', NULL, NULL, NULL, NULL, NULL);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user2', 'user2', 'user2@naver.com', '파트너스', NULL, 'FALSE', 'TRUE', NULL, NULL, NULL, NULL, NULL);

INSERT INTO PF_USER 
VALUES(PF_USER_SEQ.NEXTVAL, 'user3', 'user3', 'user3@naver.com', '클라이언트', NULL, 'FALSE', 'TRUE', NULL, NULL, NULL, NULL, NULL);

INSERT INTO PF_PROFILE
VALUES(PF_PROFILE_SEQ.NEXTVAL, 2, '개발자', '활동가능', NULL);

INSERT INTO PF_PROFILE
VALUES(PF_PROFILE_SEQ.NEXTVAL, 3, NULL, NULL, NULL);

INSERT INTO PF_COIN
VALUES(PF_COIN_SEQ.NEXTVAL,1,SYSDATE,200000,'충전');

INSERT INTO PF_BOARD
VALUES(PF_BOARD_SEQ.NEXTVAL,'테스트2222','테스트2',100000,3,'2019-01-10','2019-02-10',3,'웹','후원',NULL,'검수중',SYSDATE,3,2,'좋아');

INSERT INTO PF_BOARD
VALUES(PF_BOARD_SEQ.NEXTVAL,'테스트3333','테스트3',100000,3,'2019-01-10','2019-02-10',3,'웹','후원',NULL,'검수중',SYSDATE,3,2,'좋아');

INSERT INTO PF_BOARD
VALUES(PF_BOARD_SEQ.NEXTVAL,'테스트4444','테스트4',100000,3,'2019-01-10','2019-02-10',3,'웹','후원',NULL,'지원자 모집 중',SYSDATE,3,null,null);

INSERT INTO PF_BOARD
VALUES(PF_BOARD_SEQ.NEXTVAL,'테스트5555','테스트5',100000,3,'2019-01-10','2019-02-10',3,'웹','후원',NULL,'지원자 모집 중',SYSDATE,3,null,null);


select * from pf_board;

commit;
rollback;