--쪽지 테이블
DROP SEQUENCE PF_MESSAGE_SEQ;
DROP TABLE PF_MESSAGE;

CREATE SEQUENCE PF_MESSAGE_SEQ;

CREATE TABLE PF_MESSAGE(
	MESSAGE_NO NUMBER PRIMARY KEY, --쪽지 번호
	MESSAGE_CONTENT VARCHAR2(500) NOT NULL, --쪽지 내용
	MESSAGE_READER VARCHAR2(100) NOT NULL, --받는 사람
	MESSAGE_SENDER VARCHAR2(100) NOT NULL, --보낸 사람
	MESSAGE_SENDDATE DATE NOT NULL, --보낸 날짜
	MESSAGE_STATE VARCHAR2(100) NOT NULL --쪽지 상태(안읽음 / 읽음)
);

INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 1','user3','user1',SYSDATE,'안읽음');
INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 리스트 테스트','user3','user1',SYSDATE,'안읽음');
INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 리스트 테스트','user3','user2',SYSDATE,'안읽음');


INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 1','user2','user3',SYSDATE,'안읽음');
INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 1','user2','user3',SYSDATE,'안읽음');
INSERT INTO PF_MESSAGE VALUES(PF_MESSAGE_SEQ.NEXTVAL,'쪽지 1','user2','user3',SYSDATE,'안읽음');

SELECT * FROM PF_MESSAGE;