DROP SEQUENCE PF_MESSAGE_SEQ;

CREATE SEQUENCE PF_MESSAGE_SEQ;

--쪽지 DB
CREATE TABLE(
	MESSAGE_N0 NUMBER PRIMARY KEY, --쪽지 번호
	MESSAGE_CONTENT VARCHAR2 NOT NULL, --쪽지 내용
	MESSAGE_READER VARCHAR2 NOT NULL, --받는 사람
	MESSAGE_SENDER VARCHAR2 NOT NULL, --보낸 사람
	MESSAGE_SENDDATE DATE NOT NULL, --보낸 날짜
	MESSAGE_STATE VARCHAR2 NOT NULL --쪽지 상태(안읽음 / 읽음)
);